name: Node.js CD Pipeline

on:
  pull_request:
    types: 
      - closed
    branches: 
      - master

jobs:
  deploy:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_DEPLOY_MESSAGE: 'Prod deploy: ${{ github.sha }}'
            NETLIFY_DEPLOY_TO_PROD: true
            build_directory: .output/public
            build_command: yarn generate
