name: Node.js CI Pipeline

on:
  pull_request:
    types: 
      - opened
      - synchronize
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install yarn
      run: npm install -g yarn

    - name: Install JS dependencies
      run: yarn install --frozen-lockfile

    - name: build
      run: yarn build

